import com.theokanning.openai.OpenAiService;
import com.theokanning.openai.completion.CompletionChoice;
import com.theokanning.openai.completion.CompletionRequest;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

/** A Utility class for the OpenAI GPT-3 Api Client in Java - https://github.com/TheoKanning/openai-java
 *  Enables easier queries to the language model
 */
public class UtilityGPT {

    /** A GPT-3 API key (if set, can use the overloaded methods that don't have an api-key parameter) */
    public static String apiKey = "";

    /** Whether the Tokens parameter should only refer to new text generated by GPT-3
     * If true, then Tokens will be automatically increased by the # of tokens in the prompt
     * Token calculation used is 1 token equates 4 english chars (https://help.openai.com/en/articles/4936856-what-are-tokens-and-how-to-count-them)
     */
    public static boolean automaticallyIncludePromptTokens = false;

    /** counter for how many language model queries have occurred, and tokens used */
    public static int queryCounter = 0, tokenCounter = 0;

    /** whether the query count & token count should be continually printed to console */
    public static boolean printQueryCounter = false;

    /** Base series models */
    public static String davinci = "davinci", curie = "curie", babbage = "babbage", ada = "ada";

    /** Instruct series models */
    public static String inDavinci = "davinci-instruct-beta-v3", inCurie = "curie-instruct-beta-v2",
            inBabbage = "babbage-instruct-beta", inAda = "ada-instruct-beta";

    /** Sets UtilityGPT.apiKey, once set, can use the overloaded methods that don't have an api-key parameter */
    public static void setApiKey(String apiKey) {
        UtilityGPT.apiKey = apiKey;
    }

    /** Sets whether the Tokens parameter should only refer to new text generated by GPT-3
     * If true, then Tokens will be automatically increased by the # of tokens in the prompt
     * Token calculation used is 1 token equates 4 english chars (https://help.openai.com/en/articles/4936856-what-are-tokens-and-how-to-count-them)
     */
    public static void setAutomaticallyIncludePromptTokens(boolean automaticallyIncludePromptTokens) {
        UtilityGPT.automaticallyIncludePromptTokens = automaticallyIncludePromptTokens;
    }


    /** Utility method for using the GPT-3 Java Api Client
     *
     * @param apiKey, A GPT-3 API key
     * @param model, GPT-3 model (can pick from UtilityGPT.model_name)
     * @param prompt, Prompt sent to the language model
     * @param tokens, If automaticallyIncludePromptTokens is false, it'll set the
     *                  number of tokens that the language model will use, between both prompt length and generation length
     * @param args, any number of String arguments, each argument should be in the format 'setting:value'
     *              Only mandatory settings are model, tokens, and if Utility.apiKey isn't set, the apiKey as well
     *              if setting starts with 'te' it'll set the temperature (default 1) a value 0-1 with 1 being very creative,
                        0 being very factual/deterministic
     *              if setting starts with 'top' it'll set the topP, (default 1) between 0-1 where 1.0 means
                        "use all tokens in the vocabulary" while 0.5 means "use only the 50% most common tokens"
     *              if setting starts with 'f' it'll set the frequencyPenalty, (default 0) 0-1, lowers the chances of a
                        word being selected again the more times that word has already been used
     *              if setting starts with 'p' it'll set the presencePenalty, (default 0) 0-1, lowers the chances of topic repetition
     *              if setting starts with 'b' it'll set the bestOf, (default 1), queries GPT-3 this many times, then
                        selects the 'best' generation to return
     *              if setting starts with 'c' it'll set cutOffLastPunctuationMark (boolean true/false, or int (0=F,1=T)),
     *                  whether GPT-3's full output should be cut off after the last detected punctuation mark
     *                  (if none found after prompt, nothing removed)
     *              if setting starts with 's' it'll set the stop sequence, the String that GPT-3 will stop generating after
                        (can have 4 stop sequences max) (leading & trailing whitespaces not removed from the value of this setting)
     * @return GPT-3's returned text (prompt + generated)
     */
    public static String query(String apiKey, String model, String prompt, int tokens, String... args) {

        if(automaticallyIncludePromptTokens) {
            tokens += prompt.length() / 4;
        }

        List<String> stopSequences = new ArrayList<>();

        try {

            int bestOf = 1;
            double temp = 1, top = 1, freq = 0, pres = 0;
            boolean cutOffLastPunctuationMark = false;

            //this flag variable will be used to set bestOf = 1 if (bestOf != 1 && isInstructModel)
            //& warn user, since the OpenAI API will throw an HTTP 500 error if an instruct model is used when bestOf != 1
            boolean isInstructModel = model.contains("instruct");;

            for (int i = 0; i < args.length; i++) {

                String key = args[i].split(":")[0].trim().toLowerCase();
                String value = key.startsWith("s") ? args[i].split(":")[1] : args[i].split(":")[1].trim();

                if (key.startsWith("te")) {
                    temp = Double.parseDouble(value);
                } else if (key.startsWith("top")) {
                    top = Double.parseDouble(value);
                } else if (key.startsWith("f")) {
                    freq = Double.parseDouble(value);
                } else if (key.startsWith("p")) {
                    pres = Double.parseDouble(value);
                } else if (key.startsWith("b")) {
                    bestOf = Integer.parseInt(value);
                } else if (key.startsWith("c")) {
                    //handle if boolean is encoded as number 0,1
                    try {
                        cutOffLastPunctuationMark = Integer.parseInt(value) == 1;
                    } catch(NumberFormatException ex) {
                        cutOffLastPunctuationMark = Boolean.parseBoolean(value);
                    }
                } else if (key.startsWith("s")) {
                    if(stopSequences.size() == 4) {
                        System.out.println("Warning: there can not be more than 4 stop sequences, ignoring the" +
                                " stop sequence \'" + value + "\'");
                    }
                    else {
                        stopSequences.add(value);
                    }
                }
                else {
                    System.out.println("Warning: setting \'" + key + "\' not recognized.  Omitting parameter [" +
                            args[i] + "]");
                }
            }

            tokenCounter += tokens;
            queryCounter++;
            if(printQueryCounter) {
                System.out.println("---------------------------------------------\n" +
                        "# of GPT-3 queries: " + queryCounter + "\nTotal tokens used: " + tokenCounter + "\n" +
                        "---------------------------------------------");
            }

            if(isInstructModel && bestOf != 1) {
                System.out.println("######################\nWarning: Instruct models must have a bestOf value = 1 " +
                        "(or HTTP 500 error thrown)\nchanging bestOf from " + bestOf + " to 1.\n######################");
                bestOf = 1;
            }

            OpenAiService service = new OpenAiService(apiKey);

            CompletionRequest.CompletionRequestBuilder completionRequestBuilder = CompletionRequest.builder()
                    .prompt(prompt)
                    .echo(true);

            completionRequestBuilder.maxTokens(tokens);
            completionRequestBuilder.temperature(temp);
            completionRequestBuilder.topP(top);
            completionRequestBuilder.frequencyPenalty(freq);
            completionRequestBuilder.presencePenalty(pres);
            completionRequestBuilder.bestOf(bestOf);
            if (stopSequences.size() > 0)
                completionRequestBuilder.stop(stopSequences);

            CompletionRequest completionRequest = completionRequestBuilder.build();
            List<CompletionChoice> outputList = service.createCompletion(model, completionRequest).getChoices();

            String output = _apiOutputCondensed(outputList.get(0).toString(), prompt.length() - 1,
                    cutOffLastPunctuationMark);

            return output;

        }catch(Exception e) {
            e.printStackTrace();
        }
        System.out.println("Error in UtilityGPT.query() - varargs passed to method: " + Arrays.toString(args));
        return "";
    }

    /** Utility method for using the GPT-3 Java Api Client
     *  Overloadeded method for use if UtilityGPT.apiKey is set
     *
     * @param model, GPT-3 model (can pick from UtilityGPT.model_name)
     * @param prompt, Prompt sent to the language model
     * @param tokens, If automaticallyIncludePromptTokens is false, it'll set the
     *                  number of tokens that the language model will use, between both prompt length and generation length
     * @param args, any number of String arguments, each argument should be in the format 'setting:value'
     *              Only mandatory settings are model, tokens, and if Utility.apiKey isn't set, the apiKey as well
     *              if setting starts with 'te' it'll set the temperature (default 1) a value 0-1 with 1 being very creative,
                        0 being very factual/deterministic
     *              if setting starts with 'top' it'll set the topP, (default 1) between 0-1 where 1.0 means
                        "use all tokens in the vocabulary" while 0.5 means "use only the 50% most common tokens"
     *              if setting starts with 'f' it'll set the frequencyPenalty, (default 0) 0-1, lowers the chances of a
                        word being selected again the more times that word has already been used
     *              if setting starts with 'p' it'll set the presencePenalty, (default 0) 0-1, lowers the chances of topic repetition
     *              if setting starts with 'b' it'll set the bestOf, (default 1), queries GPT-3 this many times, then
                        selects the 'best' generation to return
     *              if setting starts with 'c' it'll set cutOffLastPunctuationMark (boolean true/false, or int (0=F,1=T)),
     *                  whether GPT-3's full output should be cut off after the last detected punctuation mark
     *                  (if none found after prompt, nothing removed)
     *              if setting starts with 's' it'll set the stop sequence, the String that GPT-3 will stop generating after
                        (can have 4 stop sequences max) (leading & trailing whitespaces not removed from the value of this setting)
     * @return GPT-3's returned text (prompt + generated)
     */
    public static String query(String model, String prompt, int tokens, String... args) {

        if(apiKey.length() == 0) {
            System.out.println("\n\nError: API key is not set.  Either use the overloaded query method requiring the " +
                            "API key parameter, or first set UtilityGPT.apiKey\n");
            return "";
        }

        if(automaticallyIncludePromptTokens) {
            tokens += prompt.length() / 4;
        }

        List<String> stopSequences = new ArrayList<>();

        try {

            int bestOf = 1;
            double temp = 1, top = 1, freq = 0, pres = 0;
            boolean cutOffLastPunctuationMark = false;

            //this flag variable will be used to set bestOf = 1 if (bestOf != 1 && isInstructModel)
            //& warn user, since the OpenAI API will throw an HTTP 500 error if an instruct model is used when bestOf != 1
            boolean isInstructModel = model.contains("instruct");;

            for (int i = 0; i < args.length; i++) {

                String key = args[i].split(":")[0].trim().toLowerCase();
                String value = key.startsWith("s") ? args[i].split(":")[1] : args[i].split(":")[1].trim();

                if (key.startsWith("te")) {
                    temp = Double.parseDouble(value);
                } else if (key.startsWith("top")) {
                    top = Double.parseDouble(value);
                } else if (key.startsWith("f")) {
                    freq = Double.parseDouble(value);
                } else if (key.startsWith("p")) {
                    pres = Double.parseDouble(value);
                } else if (key.startsWith("b")) {
                    bestOf = Integer.parseInt(value);
                } else if (key.startsWith("c")) {
                    //handle if boolean is encoded as number 0,1
                    try {
                        cutOffLastPunctuationMark = Integer.parseInt(value) == 1;
                    } catch(NumberFormatException ex) {
                        cutOffLastPunctuationMark = Boolean.parseBoolean(value);
                    }
                } else if (key.startsWith("s")) {
                    if(stopSequences.size() == 4) {
                        System.out.println("Warning: there can not be more than 4 stop sequences, ignoring the" +
                                " stop sequence \'" + value + "\'");
                    }
                    else {
                        stopSequences.add(value);
                    }
                }
                else {
                    System.out.println("Warning: setting \'" + key + "\' not recognized.  Omitting parameter [" +
                            args[i] + "]");
                }
            }

            tokenCounter += tokens;
            queryCounter++;
            if(printQueryCounter) {
                System.out.println("---------------------------------------------\n" +
                        "# of GPT-3 queries: " + queryCounter + "\nTotal tokens used: " + tokenCounter + "\n" +
                        "---------------------------------------------");
            }

            if(isInstructModel && bestOf != 1) {
                System.out.println("######################\nWarning: Instruct models must have a bestOf value = 1 " +
                        "(or HTTP 500 error thrown)\nchanging bestOf from " + bestOf + " to 1.\n######################");
                bestOf = 1;
            }

            OpenAiService service = new OpenAiService(apiKey);

            CompletionRequest.CompletionRequestBuilder completionRequestBuilder = CompletionRequest.builder()
                    .prompt(prompt)
                    .echo(true);

            completionRequestBuilder.maxTokens(tokens);
            completionRequestBuilder.temperature(temp);
            completionRequestBuilder.topP(top);
            completionRequestBuilder.frequencyPenalty(freq);
            completionRequestBuilder.presencePenalty(pres);
            completionRequestBuilder.bestOf(bestOf);
            if (stopSequences.size() > 0)
                completionRequestBuilder.stop(stopSequences);

            CompletionRequest completionRequest = completionRequestBuilder.build();
            List<CompletionChoice> outputList = service.createCompletion(model, completionRequest).getChoices();

            String output = _apiOutputCondensed(outputList.get(0).toString(), prompt.length() - 1,
                    cutOffLastPunctuationMark);

            return output;

        }catch(Exception e) {
            e.printStackTrace();
        }
        System.out.println("Error in UtilityGPT.query() - varargs passed to method: " + Arrays.toString(args));
        return "";
    }


    /**
     *  Extracts the language model's raw output from the output of the GPT-3 Java Api Client
     *
     * @param output, what is outputted by an OpenAiService object calling the methods -
     *                createCompletion(model, completionRequest).getChoices().get(0).toString()
     * @param punctuationIgnoreIndex, if cutOffLastPunctuationMark is true,
     *                                any punctuation marks <= punctuationIgnoreIndex will be ignored
     * @param cutOffLastPunctuationMark, whether GPT-3's full output should be cut off at the last detected punctuation mark
     * @return Language model's raw output
     */
    public static String _apiOutputCondensed(String output, int punctuationIgnoreIndex, boolean cutOffLastPunctuationMark) {
        //start inclusive, end exclusive
        int endIndex = 0, startIndex = output.indexOf('=') + 1;
        for(int i = output.length() - 1, commaCount = 0; i >= 0 && endIndex == 0; i--) {
            if(output.charAt(i) == ',') {
                commaCount++;
            }
            if(commaCount == 3) {
                endIndex = i;
            }
        }
        String format = output.substring(startIndex, endIndex);
        if(cutOffLastPunctuationMark) {
            if(format.contains(".") || format.contains("!") || format.contains("?")) {
                //index will be -1 if char not found
                int periodIndex = format.lastIndexOf('.');
                int exclamationIndex = format.lastIndexOf('!');
                int questionIndex = format.lastIndexOf('?');

                if(periodIndex > exclamationIndex && periodIndex > questionIndex && periodIndex > punctuationIgnoreIndex)
                    return format.substring(0, periodIndex + 1);
                else if(exclamationIndex > questionIndex && exclamationIndex > punctuationIgnoreIndex)
                    return format.substring(0, exclamationIndex + 1);
                else if(questionIndex > punctuationIgnoreIndex)
                    return format.substring(0, questionIndex + 1);
            }
        }

        return format;
    }

}
